property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 0
  onnx-file: /opt/models/active/lpdnet.onnx
  model-engine-file: /opt/models/active/lpdnet.engine
  labelfile-path: /opt/models/active/labels/labels_lpd.txt
  batch-size: 3
  network-mode: 0
  num-detected-classes: 1
  interval: 0
  gie-unique-id: 2
  process-mode: 2
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  infer-dims: 3;480;640
  parse-bbox-func-name: NvDsInferParseBbox
  operate-on-gie-id: 1
  operate-on-class-ids: 0

class-attrs-all:
  pre-cluster-threshold: 0.3
  topk: 100
  nms-iou-threshold: 0.5
  roi-top-offset: 0
  roi-bottom-offset: 0
  detected-min-w: 0
  detected-min-h: 0
