property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 0
  onnx-file: /opt/models/active/lprnet.onnx
  model-engine-file: /opt/models/active/lprnet.engine
  labelfile-path: /opt/models/active/labels/labels_lpr.txt
  batch-size: 3
  network-mode: 0
  num-detected-classes: 30
  interval: 0
  gie-unique-id: 3
  process-mode: 2
  network-type: 1
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  infer-dims: 3;48;96
  parse-bbox-func-name: NvDsInferParseBbox
  operate-on-gie-id: 2
  operate-on-class-ids: 0
  input-object-min-height: 30
  input-object-min-width: 40

class-attrs-all:
  pre-cluster-threshold: 0.5
  nms-iou-threshold: 0.5
  roi-top-offset: 0
  roi-bottom-offset: 0
