# Generated by Django 6.0.6 on 2026-07-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('host', models.CharField(max_length=120)),
                ('port', models.IntegerField(default=80)),
                ('username', models.CharField(blank=True, default='', max_length=80)),
                ('password', models.CharField(blank=True, default='', max_length=80)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('firmware', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('hardware_id', models.CharField(blank=True, default='', max_length=120)),
                ('xaddrs', models.TextField(blank=True, default='')),
                ('scopes', models.TextField(blank=True, default='')),
                ('is_online', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('stream_uris', models.JSONField(blank=True, default=dict)),
                ('camera_specs', models.JSONField(blank=True, default=dict)),
                ('default_profile_token', models.CharField(blank=True, default='', max_length=120)),
                ('motion_active', models.BooleanField(default=False)),
                ('event_listener_enabled', models.BooleanField(default=False)),
                ('deepstream_enabled', models.BooleanField(default=False)),
                ('deepstream_pipeline', models.CharField(choices=[('aduana', 'Aduana - Contenedores'), ('', 'Sin pipeline')], default='aduana', max_length=20)),
                ('source_type', models.CharField(choices=[('rtsp', 'RTSP Camera'), ('file', 'File (MP4)')], default='rtsp', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('snmp_enabled', models.BooleanField(default=False)),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=64)),
                ('snmp_port', models.IntegerField(default=161)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='operadores.site')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=20)),
                ('index', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Device events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('dwell_seconds', models.IntegerField(default=10)),
                ('speed', models.FloatField(default=1.0)),
                ('preset_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_token', models.CharField(max_length=120)),
                ('preset_name', models.CharField(blank=True, default='', max_length=120)),
                ('shapes', models.JSONField(blank=True, default=list)),
                ('ptz_position', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_presets', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'preset_token'],
                'unique_together': {('device', 'preset_token')},
            },
        ),
        migrations.CreateModel(
            name='IVSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('rule_type', models.CharField(choices=[('CrossLine', 'Cross Line (Tripwire)'), ('CrossRegion', 'Cross Region (Intrusion)'), ('SmartMotion', 'Smart Motion'), ('ParkingDetection', 'Parking Detection'), ('VideoMotion', 'Video Motion')], default='CrossLine', max_length=40)),
                ('enable', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('A->B', 'A → B'), ('B->A', 'B → A'), ('Both', 'Both')], default='Both', max_length=10)),
                ('detect_line', models.TextField(blank=True, default='')),
                ('detect_region', models.TextField(blank=True, default='')),
                ('event_handler', models.JSONField(blank=True, default=dict)),
                ('camera_rule_id', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivs_rules', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'index'],
                'unique_together': {('device', 'index')},
            },
        ),
    ]
