# Generated by Django 6.0.5 on 2026-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('host', models.CharField(max_length=120)),
                ('port', models.IntegerField(default=80)),
                ('username', models.CharField(blank=True, default='', max_length=80)),
                ('password', models.CharField(blank=True, default='', max_length=80)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('firmware', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('hardware_id', models.CharField(blank=True, default='', max_length=120)),
                ('xaddrs', models.TextField(blank=True, default='')),
                ('scopes', models.TextField(blank=True, default='')),
                ('is_online', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
