# Generated by Django 6.0.5 on 2026-05-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='stream_uris',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
