# Generated by Django 6.0.5 on 2026-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_stream_uris'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='camera_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
