# Generated by Django 6.0.5 on 2026-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_camera_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default_profile_token',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
