# Generated by Django 6.0.5 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_default_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='motion_active',
            field=models.BooleanField(default=False),
        ),
    ]
