# Generated by Django 6.0.5 on 2026-05-16 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_motion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='event_listener_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=20)),
                ('index', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device')),
            ],
            options={
                'verbose_name_plural': 'Device events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IVSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('rule_type', models.CharField(choices=[('CrossLine', 'Cross Line (Tripwire)'), ('CrossRegion', 'Cross Region (Intrusion)'), ('SmartMotion', 'Smart Motion'), ('ParkingDetection', 'Parking Detection'), ('VideoMotion', 'Video Motion')], default='CrossLine', max_length=40)),
                ('enable', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('A->B', 'A → B'), ('B->A', 'B → A'), ('Both', 'Both')], default='Both', max_length=10)),
                ('detect_line', models.TextField(blank=True, default='')),
                ('detect_region', models.TextField(blank=True, default='')),
                ('event_handler', models.JSONField(blank=True, default=dict)),
                ('camera_rule_id', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivs_rules', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'index'],
                'unique_together': {('device', 'index')},
            },
        ),
    ]
