# Generated by Django 6.0.5 on 2026-06-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_analyticspreset_ptz_position'),
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='operadores.site'),
        ),
    ]
