# Generated by Django 6.0.5 on 2026-06-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deepstream_pipeline',
            field=models.CharField(choices=[('main', 'Peoplenet'), ('facerec', 'Face Recognition'), ('yolov9', 'YOLO v9')], default='main', max_length=20),
        ),
    ]
