# Generated by Django 6.0.6 on 2026-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_device_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deepstream_pipeline',
            field=models.CharField(choices=[('main', 'Peoplenet'), ('facerec', 'Face Recognition'), ('yolov9', 'YOLO v9'), ('trafficcamnet_lpr', 'TrafficCamNet + LPR')], default='main', max_length=20),
        ),
    ]
