# Generated by Django 6.0.6 on 2026-06-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_alter_device_deepstream_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_port',
            field=models.IntegerField(default=161),
        ),
        migrations.AlterField(
            model_name='device',
            name='deepstream_pipeline',
            field=models.CharField(choices=[('main', 'Peoplenet'), ('retinaface', 'Face Recognition'), ('yolov9', 'YOLO v9'), ('trafficcamnet_lpr', 'TrafficCamNet + LPR'), ('', 'Sin pipeline')], default='main', max_length=20),
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('dwell_seconds', models.IntegerField(default=10)),
                ('speed', models.FloatField(default=1.0)),
                ('preset_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'name'],
            },
        ),
    ]
