# Generated by Django 6.0.6 on 2026-07-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_code', models.CharField(blank=True, default='', max_length=32)),
                ('seal_status', models.CharField(choices=[('con_sello', 'Con Sello'), ('sin_sello', 'Sin Sello'), ('indeterminado', 'Indeterminado'), ('processing', 'Procesando')], default='processing', max_length=16)),
                ('seal_confidence', models.FloatField(default=0.0)),
                ('timestamp_start', models.DateTimeField(db_index=True)),
                ('timestamp_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp_start'],
            },
        ),
        migrations.CreateModel(
            name='ContainerDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(default=0)),
                ('class_id', models.IntegerField(choices=[(0, 'con_sello'), (1, 'cont data'), (2, 'sin_sello'), (3, 'container cod')])),
                ('object_id', models.BigIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox_left', models.FloatField()),
                ('bbox_top', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('crop', models.ImageField(max_length=255, upload_to='crops/%Y/%m/%d/')),
                ('ocr_text', models.CharField(blank=True, default='', max_length=64)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_detections', to='devices.device')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='aduana.containerevent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='aduana_cont_device__41da7a_idx'), models.Index(fields=['event', 'class_id'], name='aduana_cont_event_i_da4f10_idx')],
            },
        ),
    ]
