# Generated by Django 6.0.6 on 2026-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdetection',
            name='ocr_texts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
