# Generated by Django 6.0.6 on 2026-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana', '0003_ocr_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerdetection',
            name='dominant_color_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containerdetection',
            name='dominant_color_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containerdetection',
            name='dominant_color_v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
