# Generated by Django 6.0.7 on 2026-08-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana', '0008_event_frames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerdetection',
            name='class_id',
            field=models.IntegerField(choices=[(0, 'con_sello'), (1, 'sin_sello'), (2, 'cont data'), (3, 'container cod'), (4, 'truck')]),
        ),
        migrations.AlterField(
            model_name='containerdetection',
            name='ocr_texts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='containerdetection',
            name='roi_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
