# Generated by Django 6.0.7 on 2026-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana', '0009_alter_containerdetection_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerevent',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Marcada para revision humana (mezcla de colores sospechosa en los crops)'),
        ),
    ]
