# Generated by Django 6.0.7 on 2026-08-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduana', '0010_containerevent_needs_review'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerdetection',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_detections', to='devices.device'),
        ),
    ]
