face-class-id: 2

source-list:
  list: "file:///opt/videos/prada.mp4;"

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 1920
  height: 1080

primary-gie:
  plugin-type: 0
  config-file-path: ../models/facerec/pgie_config.yml

secondary-gie0:
  plugin-type: 0
  config-file-path: ../models/facerec/sgie0_config.yml

secondary-gie1:
  plugin-type: 0
  config-file-path: ../models/facerec/sgie1_config.yml
analytics:
  enable: 1
  config-file: config_nvdsanalytics.txt

osd:
  process-mode: 0
  display-text: 1

tiler:
  width: 1280
  height: 720

sink:
  qos: 0
