property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 0
  tlt-model-key: nvidia_tlt
  tlt-encoded-model: /opt/models/active/model.etlt
  model-engine-file: /opt/models/active/model.engine
  labelfile-path: /opt/models/active/labels/labels.txt
  int8-calib-file: /opt/models/active/int8_calibration.txt
  uff-input-blob-name: input_1
  output-blob-names: output_bbox/BiasAdd;output_cov/Sigmoid
  infer-dims: 3;416;736
  batch-size: 3
  network-mode: 0
  num-detected-classes: 1
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  parse-bbox-func-name: NvDsInferParseBbox

class-attrs-all:
  pre-cluster-threshold: 0.5
  topk: 100
  nms-iou-threshold: 0.5
