# Generated by Django 6.0.5 on 2026-05-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0011_analyticspreset_ptz_position'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('webhook', 'Webhook')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_codes', models.JSONField(blank=True, default=list)),
                ('analytics_trigger', models.JSONField(blank=True, default=list)),
                ('min_objects', models.IntegerField(default=0)),
                ('cooldown_seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('message_template', models.TextField(blank=True, default='')),
                ('send_immediate', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='notifications.notificationchannel')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='devices.device')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='incidents.incidenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
