# Generated by Django 6.0.5 on 2026-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('timeout_seconds', models.IntegerField()),
                ('requires_ack', models.BooleanField(default=True)),
                ('message_template', models.TextField(blank=True, default='')),
                ('auto_actions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['incident_type', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='active', max_length=20)),
                ('current_level', models.IntegerField(default=1)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('level_started_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('action', models.CharField(max_length=40)),
                ('success', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_resolve_seconds', models.IntegerField(default=0)),
                ('dedup_window_seconds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
