# Generated by Django 6.0.5 on 2026-05-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0011_analyticspreset_ptz_position'),
        ('incidents', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationlevel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel'),
        ),
        migrations.AddField(
            model_name='incident',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='devices.device'),
        ),
        migrations.AddField(
            model_name='incident',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationrule'),
        ),
        migrations.AddField(
            model_name='incidentlog',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidenttype'),
        ),
        migrations.AddField(
            model_name='escalationlevel',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='incidents.incidenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='escalationlevel',
            unique_together={('incident_type', 'level')},
        ),
    ]
