# Generated by Django 5.2.17 on 2026-09-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('cam', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('estado', models.CharField(default='pendiente', max_length=12)),
                ('etiqueta', models.CharField(blank=True, choices=[('con', 'CON SELLO'), ('sin', 'SIN SELLO'), ('duda', 'DUDA')], max_length=6, null=True)),
                ('guardado_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
